name: Alignment Unit Test

on:
  push:
    branches: 
      - main
      - nf-test
  pull_request:
    branches:
      - main
      - nf-test

jobs:
  alignment-test:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '11'

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: '24.10.5'

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true
          channels: bioconda,conda-forge,defaults

      - name: Pull custom Docker image
        run: |
          docker pull e10m/bwa-and-samtools:latest

      - name: Install nf-test
        run: |
          conda install bioconda::nf-test

      - name: Run nf-test
        working-directory: ./nextflow_automation/data_processing
        run: |
          nf-test test --profile docker