name: Alignment Unit Test

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - main

jobs:
    test_align:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup nf-test
              uses: ./.github/actions/setup-nf-test
            
            - name: Pull custom Docker image
              run: docker pull e10m/bwa-and-samtools:latest

            - name: Run alignment test
              shell: bash -el {0}
              working-directory: ./nextflow_automation/data_processing/
              run: nf-test test tests/modules/align.nf.test
